# Generated by Django 4.2 on 2023-04-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='images/')),
                ('image', models.FileField(upload_to='images/')),
                ('title', models.CharField(max_length=225)),
                ('pub_date', models.DateTimeField()),
                ('body', models.CharField()),
                ('url', models.URLField()),
            ],
        ),
    ]
